#!/usr/bin/env bash
# Regenerate (or verify) catalog.json - the dawo.* option vocabulary
# (ADR 0005) that this overlay commits by hand and the console reads at
# runtime to render settings.
#
# catalog.json is derived output: it comes from evaluating this flake's
# `catalog` attribute (nix/export-catalog.nix, fed by demo-core.nix's
# documented dawo.* options), per the comment above that output in
# flake.nix ("Regenerate with: nix eval .#catalog --json > catalog.json").
# Nothing currently regenerates or verifies it in CI (audit finding:
# "catalog.json is a hand-regenerated artifact with no drift gate"), so
# editing an option's description/default, or adding a new documented
# option, ships a stale settings vocabulary with no build-time signal.
#
# hardware-profiles.json is NOT generated by this script: unlike catalog.json
# it is hand-authored operator-facing metadata (imaging steps, disko notes)
# that has no corresponding flake output to diff against (see
# internal/domain/fleet/hardware.go and flake.nix's hardwareProfiles attrset,
# whose profile *names* are cross-checked at eval time by
# nix/generator.nix's deviceAsserts, not by this script).
#
# Usage:
#   examples/overlay/regen-catalog.sh          # regenerate catalog.json in place
#   examples/overlay/regen-catalog.sh --check  # fail (exit 1) if the committed
#                                               # file differs from a fresh
#                                               # export - wire this into CI
#                                               # (.forgejo/workflows/ci.yml) as
#                                               # a job step, e.g.:
#                                               #   - run: examples/overlay/regen-catalog.sh --check
set -euo pipefail
cd "$(dirname "$0")"

CHECK=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK=1
fi

OUT=catalog.json
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

nix eval --json .#catalog | python3 -m json.tool --sort-keys >"$tmp"

if [[ "$CHECK" == "1" ]]; then
  if ! diff -u "$OUT" "$tmp"; then
    echo "error: $OUT is stale - regenerate with examples/overlay/regen-catalog.sh" >&2
    exit 1
  fi
  echo "$OUT matches the flake's catalog export"
else
  cp "$tmp" "$OUT"
  echo "wrote $OUT"
fi
