package web

// catalog.go holds the console message catalog: locale -> key -> text.
// English is the source language and fallback; Dutch translates the
// operator-facing UI. Generated-then-curated; keep keys sorted. A missing
// key falls back to English, then renders the key itself so gaps are visible.

// catalog maps locale -> key -> translation. A missing key falls back to
// English; a missing English key renders the key itself, which makes an
// untranslated string visible instead of silently blank.
var catalog = map[string]map[string]string{
	"en": {
		"access.active_bindings":               "Active role bindings",
		"access.approval_desc":                 "How changes and updates must be reviewed before they take effect.",
		"access.approval_flows":                "Approval flows",
		"access.bindings_suffix":               "bindings",
		"access.dir_not_configured":            "directory browse not configured; type the group name",
		"access.four_eyes_desc":                "a change may not be merged by its own author (segregation of duties).",
		"access.four_eyes_label":               "Four-eyes",
		"access.grant_desc":                    "Bind an IdP group to a role within a scope.",
		"access.grant_title":                   "Grant access",
		"access.intro":                         "Role bindings grant IdP groups a role at a scope. Bindings are part of the fleet configuration: every change is a gated, audited git commit.",
		"access.no_bindings":                   "No bindings; only server-configured baseline groups apply.",
		"access.require_change_desc":           "configuration edits must go through a reviewed change, never a direct commit.",
		"access.require_change_label":          "Require change-request",
		"access.require_testwave_desc":         "a rollout must have a gated test wave first; an owner can skip it per rollout.",
		"access.require_testwave_label":        "Require test wave",
		"access.save_approval_flows":           "Save approval flows",
		"access.select_role":                   "Select a role...",
		"access.stage_binding":                 "Stage binding",
		"access.title":                         "Access control",
		"audit.commit":                         "Commit",
		"audit.commit_trail":                   "Configuration commit trail",
		"audit.download_bundle":                "Download JSON bundle",
		"audit.entries_label":                  "entries",
		"audit.evidence_desc":                  "Download a signed JSON bundle for a period: every change, who approved it, and what rolled out. For auditors and compliance reviews.",
		"audit.evidence_export":                "Evidence export",
		"audit.from_date":                      "From date",
		"audit.intro":                          "Review configuration changes and access history. Every change is a signed git commit.",
		"audit.no_history":                     "No history available.",
		"audit.title":                          "Audit trail",
		"audit.to_date":                        "To date",
		"audit.what":                           "What",
		"audit.when":                           "When",
		"audit.who":                            "Who",
		"changes.abandon":                      "Abandon",
		"changes.build":                        "Build",
		"changes.clear_instead":                "clear instead",
		"changes.count_suffix":                 "changes",
		"changes.diff_link":                    "Diff",
		"changes.empty":                        "No changes yet.",
		"changes.id_label":                     "Change id",
		"changes.intro":                        "A change stages edits on a branch, builds against the gate, and merges under four-eyes. Everything is a git commit.",
		"changes.merge":                        "Merge",
		"changes.open_button":                  "Open change",
		"changes.open_title":                   "Open a change",
		"changes.review":                       "Review queue",
		"changes.setting_key_placeholder":      "setting key",
		"changes.slug_placeholder":             "lowercase slug",
		"changes.stage_button":                 "Stage",
		"changes.stage_edit":                   "Stage edit",
		"changes.title_label":                  "Title",
		"changes.title_placeholder":            "what does this change do?",
		"changes.value_placeholder":            "value",
		"common.actions":                       "Actions",
		"common.add":                           "+ new",
		"common.apply":                         "Apply",
		"common.asset_tag":                     "Asset tag",
		"common.cancel":                        "Cancel",
		"common.ceiling":                       "Ceiling",
		"common.class":                         "Class",
		"common.clear":                         "Clear",
		"common.comma_separated":               "comma-separated",
		"common.continue":                      "Continue",
		"common.cpu":                           "CPU",
		"common.create":                        "Create",
		"common.created":                       "Created",
		"common.delete":                        "Delete",
		"common.description":                   "Description",
		"common.device":                        "Device",
		"common.disk":                          "Disk",
		"common.download":                      "Download",
		"common.edit":                          "edit",
		"common.eg":                            "e.g.",
		"common.enforce":                       "Enforce",
		"common.expires":                       "Expires",
		"common.false":                         "false",
		"common.firmware":                      "Firmware",
		"common.group":                         "Group",
		"common.groups":                        "Groups",
		"common.hardware":                      "Hardware",
		"common.hardware_profile":              "Hardware profile",
		"common.id":                            "ID",
		"common.idp_group":                     "IdP group",
		"common.inherit":                       "inherit",
		"common.lastused":                      "Last used",
		"common.locked":                        "locked",
		"common.memory":                        "Memory",
		"common.model":                         "Model",
		"common.name":                          "Name",
		"common.never":                         "never",
		"common.never_seen":                    "never seen",
		"common.new_short":                     "+ new",
		"common.no_group":                      "No group",
		"common.none":                          "none",
		"common.offline":                       "offline",
		"common.online":                        "online",
		"common.optional":                      "optional",
		"common.org_default":                   "organisation default",
		"common.organisation":                  "Organisation",
		"common.profile":                       "Profile",
		"common.remove":                        "Remove",
		"common.revoke":                        "Revoke",
		"common.role":                          "Role",
		"common.save":                          "Save",
		"common.scope":                         "Scope",
		"common.select":                        "Select...",
		"common.serial":                        "Serial",
		"common.status":                        "Status",
		"common.tag":                           "Tag",
		"common.true":                          "true",
		"common.ttl_days":                      "TTL (days)",
		"common.unknown":                       "unknown",
		"common.user":                          "User",
		"common.value":                         "Value",
		"common.vendor":                        "Vendor",
		"common.withdraw":                      "Withdraw",
		"device.armed_label":                   "Armed:",
		"device.assign_user":                   "Assign user",
		"device.assigned_user":                 "Assigned user",
		"device.assigned_user_placeholder":     "assigned user",
		"device.attention":                     "attention",
		"device.class_placeholder":             "class (laptop, kiosk)",
		"device.col_enforced":                  "Enforced",
		"device.col_provenance":                "Provenance",
		"device.col_setting":                   "Setting",
		"device.complete":                      "complete",
		"device.confirm_wipe_label":            "Type the tag to confirm a wipe",
		"device.cores":                         "cores",
		"device.credential_hint":               "Store it now; it is not shown again. The device checks in as itself with it.",
		"device.credential_label":              "One-shot credential",
		"device.effective_config":              "Effective configuration",
		"device.executed":                      "executed",
		"device.facts_title":                   "Hardware facts (nixos-facter)",
		"device.hardware_spec_title":           "Hardware specification",
		"device.identity_title":                "Identity",
		"device.last_seen":                     "Last seen",
		"device.lock_device":                   "Lock device",
		"device.locked_title":                  "locked",
		"device.lost_stolen_desc":              "Lost or stolen device. Lock is reversible; wipe destroys the disk encryption keys and is irreversible. Every action is an audited commit.",
		"device.manage_desc":                   "Administrative actions for assignment and lifecycle state. Every change is a gated, signed git commit.",
		"device.manage_title":                  "Manage device",
		"device.managed_apps":                  "Managed applications",
		"device.next_label":                    "Next:",
		"device.no_apps":                       "No applications assigned.",
		"device.nothing_configured":            "Nothing configured yet.",
		"device.open_editor":                   "Open editor",
		"device.overridable_title":             "overridable",
		"device.pending_delivery":              "pending delivery on next check-in",
		"device.posture_waiting":               "Waiting for a posture-aware check-in from the device agent.",
		"device.raw_document":                  "raw document",
		"device.reactivate":                    "Reactivate",
		"device.reactivate_hint":               "returns to service with a fresh credential",
		"device.reissue_credential":            "Re-issue credential",
		"device.remote_actions_title":          "Remote actions",
		"device.reported":                      "Reported",
		"device.retire":                        "Retire",
		"device.retired":                       "retired",
		"device.sb_audit_mode":                 "audit mode",
		"device.sb_enforcing":                  "enforcing",
		"device.sb_off":                        "off",
		"device.secure_boot":                   "Secure Boot",
		"device.security_posture":              "Security posture",
		"device.set_class":                     "Set class",
		"device.set_groups":                    "Set groups",
		"device.tpm2_absent":                   "absent",
		"device.tpm2_enrolled":                 "enrolled",
		"device.tpm2_present_unbound":          "present, not bound",
		"device.tpm2_unlock":                   "TPM2 unlock",
		"device.type_overlay":                  "Overlay",
		"device.type_package":                  "Package",
		"device.wipe_device":                   "Wipe device",
		"device.wipe_failed":                   "wipe failed - not fully erased",
		"device.wipe_refused":                  "refused by device (not armed / not locked)",
		"devices.device_class":                 "Device class",
		"devices.enroll_device":                "Enroll device",
		"devices.fast_enrollment":              "Fast Enrollment",
		"devices.gitops_managed":               "Git-Ops managed",
		"devices.no_devices":                   "No devices enrolled yet.",
		"devices.primary_group":                "Primary group",
		"devices.subtitle":                     "Provision new hardware and manage active assignments. Every change to a device is a gated, signed git commit.",
		"devices.title":                        "Device Fleet",
		"devices.validated_hint":               "Validated by the gate, committed to git.",
		"diff.by":                              "by",
		"diff.no_changes":                      "No changes on this branch yet.",
		"enroll.batch_desc":                    "Tick the devices below, then enrol them all onto one profile and group. Each device is tagged",
		"enroll.batch_title":                   "Enrol many at once",
		"enroll.cancel_job_title":              "Cancel job",
		"enroll.device_tag":                    "Device tag",
		"enroll.devices_on":                    "Devices on",
		"enroll.disk_suffix":                   "disk",
		"enroll.dispatch_selected":             "Dispatch imaging to selected",
		"enroll.dispatch_single":               "Dispatch imaging",
		"enroll.image_device":                  "Image this device",
		"enroll.imaging_steps":                 "Imaging steps",
		"enroll.jobs_title":                    "Imaging jobs",
		"enroll.no_stations_post":              "page first.",
		"enroll.no_stations_pre":               "No imaging stations are registered yet. Register one on the",
		"enroll.on_pxe":                        "on PXE",
		"enroll.profile_name_placeholder":      "profile name",
		"enroll.pxe_empty":                     "Nothing on the PXE network yet. Boot a device on this station's imaging network and it appears here.",
		"enroll.seen_prefix":                   "seen",
		"enroll.select_station":                "Select a station...",
		"enroll.status_canceled":               "canceled",
		"enroll.status_failed":                 "failed",
		"enroll.status_imaging":                "imaging",
		"enroll.status_installed":              "installed",
		"enroll.status_pending":                "pending",
		"enroll.step1_title":                   "Imaging station",
		"enroll.subtitle":                      "Image devices from an imaging station: pick a station, see what is on its PXE network, and enrol one machine with brand-specific guidance or a whole rack at once.",
		"enroll.suggested":                     "suggested",
		"enroll.tag_prefix":                    "Tag prefix",
		"enroll.title":                         "Enrollment",
		"error.back":                           "Go back",
		"error.title":                          "That did not go through",
		"footer.aria_resources":                "Resources",
		"footer.audit":                         "Audit log",
		"footer.docs":                          "Documentation",
		"footer.status":                        "System status",
		"footer.support":                       "Support",
		"footer.tagline":                       "NixOS fleet control plane",
		"groups.create":                        "Create group",
		"groups.create_heading":                "Create a group",
		"groups.details_title":                 "Group details",
		"groups.device_count":                  "Device count",
		"groups.empty":                         "No groups yet.",
		"groups.follows_head":                  "follows HEAD",
		"groups.hierarchy_title":               "Organization hierarchy",
		"groups.idp_group_placeholder":         "IdP group",
		"groups.idp_mapped":                    "IdP mapped",
		"groups.idp_mapping":                   "IdP mapping",
		"groups.intro":                         "Hierarchical device groups, identity-provider mappings and pin status. Policy resolves org → parent groups → group → device; enforced values flow down.",
		"groups.legend_devices":                "Devices",
		"groups.legend_idp":                    "IdP",
		"groups.legend_pinned":                 "Pinned",
		"groups.map_button":                    "Map",
		"groups.map_idp":                       "Map IdP group",
		"groups.move":                          "Move",
		"groups.none_option":                   "- none -",
		"groups.not_mapped":                    "not mapped",
		"groups.open_settings":                 "Open settings",
		"groups.owner_actions":                 "Owner actions",
		"groups.parent":                        "Parent",
		"groups.pin_field":                     "Pin",
		"groups.pinned_badge":                  "pinned",
		"groups.pinned_to":                     "Pinned to",
		"groups.remove_group":                  "Remove group",
		"groups.reparent":                      "Re-parent",
		"groups.root":                          "(root)",
		"groups.select_hint":                   "Select a group from the hierarchy to see its details and owner actions.",
		"groups.slug_placeholder":              "lowercase slug",
		"groups.title":                         "Fleet groups",
		"groups.unmapped":                      "Unmapped",
		"groups.unmapped_option":               "- unmapped -",
		"layout.breadcrumb_aria":               "Breadcrumb",
		"layout.enroll_device":                 "Enroll device",
		"layout.enroll_title":                  "Enroll a device",
		"layout.review_changes_title":          "Review pending changes",
		"layout.section_configuration":         "Configuration",
		"layout.section_fleet":                 "Fleet",
		"layout.section_governance":            "Governance",
		"layout.section_shipping":              "Shipping",
		"layout.staged_rollout_title":          "Staged rollout",
		"layout.tagline":                       "Fleet Control Plane",
		"layout.unread_suffix":                 "unread",
		"nav.access":                           "Access",
		"nav.audit":                            "Audit",
		"nav.changes":                          "Changes",
		"nav.delivery":                         "Delivery",
		"nav.devices":                          "Devices",
		"nav.enroll":                           "Enrollment",
		"nav.groups":                           "Groups",
		"nav.integrations":                     "Integrations",
		"nav.mail":                             "E-mail (SMTP)",
		"nav.org":                              "Organisation",
		"nav.profile":                          "Profile",
		"org.title":                            "Organisation settings",
		"org.subtitle":                         "Global settings for this organisation. Sextant runs one deployment per organisation, so these apply fleet-wide.",
		"org.mail_desc":                        "Configure how this organisation sends notification e-mail (SMTP).",
		"org.sa_desc":                          "Machine credentials for CI and automation.",
		"org.audit_desc":                       "Who changed what, and when.",
		"org.overlays_desc":                    "Reusable Nix overlay modules published to the fleet.",
		"org.secrets_desc":                     "References to secrets that live in the secret store.",
		"org.stations_desc":                    "Set up imaging stations that enroll new devices.",
		"org.defaults":                         "Presentation defaults",
		"org.default_locale":                   "Language",
		"org.default_timezone":                 "Timezone",
		"org.defaults_help":                    "Organisation defaults set at deployment; a user's own preferences override them.",
		"nav.overlays":                         "Overlays",
		"nav.overview":                         "Overview",
		"nav.pipeline":                         "Pipeline",
		"nav.policies":                         "Policies",
		"nav.rollout":                          "Rollout",
		"nav.secrets":                          "Secrets",
		"nav.serviceaccounts":                  "Service accounts",
		"nav.settings":                         "Settings",
		"nav.signout":                          "Sign out",
		"nav.stations":                         "Imaging stations",
		"overlays.help_text":                   "Imported by every device whose scope selects this overlay. It must evaluate and build, or the save is rejected.",
		"overlays.intro_post":                  "options they appear in Settings and Integrations to tune per scope. Overlays are additive down the scope chain.",
		"overlays.intro_pre":                   "Code once, manage via the interface. Write a custom Nix module for a device class (IoT, k8s node, POS terminal) here - each save must pass the Nix eval gate before it commits. Then manage it without touching code: assign it to a scope (org, group or device) from Settings, and if the module declares",
		"overlays.module_label":                "Module (Nix)",
		"overlays.modules_title":               "Modules",
		"overlays.name_label":                  "Overlay name",
		"overlays.new_overlay_label":           "new overlay",
		"overlays.none_yet":                    "No overlays yet. Write your first one on the right.",
		"overlays.save_validate":               "Save & validate",
		"overlays.start_template":              "Start from a class template",
		"overlays.title":                       "Overlays",
		"page.integrations.available":          "available",
		"page.integrations.clear":              "Clear",
		"page.integrations.inherit":            "inherit",
		"page.integrations.no_secrets":         "no secrets registered -",
		"page.integrations.none":               "none",
		"page.integrations.not_published":      "not published",
		"page.integrations.not_published_post": "options yet. Add the module to the overlay and export the catalog to configure it here.",
		"page.integrations.not_published_pre":  "This overlay has not published",
		"page.integrations.not_set":            "not set",
		"page.integrations.open_editor":        "Open in the configuration editor",
		"page.integrations.register_one":       "register one",
		"page.integrations.register_title":     "Register a new secret reference",
		"page.integrations.risk_suffix":        "risk",
		"page.integrations.secret_tag":         "secret",
		"page.integrations.subtitle":           "Connect the fleet to NetBird, your directory and Wazuh. These are device-side options the overlay publishes in the catalog; set them once at the organisation and they flow down to every device. Secret values are stored as references (never the secret itself).",
		"page.mail.from":                       "From address",
		"page.mail.host":                       "SMTP host",
		"page.mail.opt_none":                   "None (local relay only)",
		"page.mail.opt_starttls":               "STARTTLS (587)",
		"page.mail.opt_tls":                    "TLS (465)",
		"page.mail.password":                   "Password",
		"page.mail.port":                       "Port",
		"page.mail.pw_disabled":                "Typing a password directly is disabled: no encryption key is configured on this instance. Use a secret reference above.",
		"page.mail.pw_placeholder_keep":        "leave blank to keep the current password",
		"page.mail.pw_placeholder_new":         "enter to store encrypted",
		"page.mail.recommended":                "(recommended)",
		"page.mail.secretref_hint":             "The password lives in agenix or a cluster Secret; Sextant reads only the name. Nothing secret enters git or the console.",
		"page.mail.secretref_label":            "Secret reference name",
		"page.mail.security":                   "Security",
		"page.mail.send_test":                  "Send a test",
		"page.mail.send_test_btn":              "Send test",
		"page.mail.send_test_hint":             "Prove the settings by sending a message. Uses the saved configuration exactly as notifications will.",
		"page.mail.send_to":                    "Send to",
		"page.mail.sent":                       "Test message sent. Check the inbox.",
		"page.mail.stored_encrypted":           "(stored encrypted)",
		"page.mail.subtitle":                   "How this organisation sends notification e-mail, on its own domain. In-app notifications always work; configure SMTP here to also deliver them by mail.",
		"page.mail.typepw_hint":                "Entered here, the password is sealed with the instance key and stored in Postgres. Leave blank to keep a reference or the existing value.",
		"page.mail.typepw_label":               "...or type a password",
		"page.mail.unavailable":                "E-mail needs the Postgres store, which is not configured on this instance.",
		"page.mail.username":                   "Username",
		"page.mail.username_hint":              "(blank = anonymous relay)",
		"page.notifications.empty":             "You're all caught up. Nothing to read.",
		"page.notifications.mark_all_read":     "Mark all read",
		"page.notifications.subtitle":          "Approvals waiting on you, changes you authored, and fleet events. Opening one marks it read.",
		"page.notifications.title":             "Notifications",
		"page.notifications.unavailable":       "Notifications need the Postgres store, which is not configured on this instance.",
		"page.notifications.unread":            "Unread",
		"page.overview.all_changes":            "All changes ->",
		"page.overview.all_devices":            "All devices ->",
		"page.overview.approval_by":            "by",
		"page.overview.approval_ready":         "- built green, ready to merge",
		"page.overview.awaiting_approval":      "Awaiting your approval",
		"page.overview.cli_desc_mid":           "and",
		"page.overview.cli_desc_post":          "first.",
		"page.overview.cli_desc_pre":           "Same actions, scriptable. Set",
		"page.overview.cli_toolbelt":           "CLI toolbelt",
		"page.overview.col_device":             "Device",
		"page.overview.col_phase":              "Phase",
		"page.overview.col_revision":           "Revision",
		"page.overview.col_state":              "State",
		"page.overview.fleet_status":           "Fleet status",
		"page.overview.legend_error":           "error",
		"page.overview.legend_prefix":          "One cell per device",
		"page.overview.needs_attention":        "Needs attention",
		"page.overview.no_checkins":            "No check-ins yet.",
		"page.overview.no_devices":             "No devices reporting yet.",
		"page.overview.recent_activity":        "Recent device activity",
		"page.overview.start_enrollment":       "Start enrollment",
		"page.overview.stat_devices":           "Devices",
		"page.overview.stat_groups":            "Groups",
		"page.overview.stat_online":            "Online",
		"page.overview.stat_open_changes":      "Open changes",
		"page.overview.stat_policies":          "Policies",
		"page.overview.subtitle":               "Live state of the fleet - every figure is real, sourced from the config plane and device check-ins.",
		"page.overview.title":                  "Fleet Overview",
		"pipeline.group_label":                 "group",
		"pipeline.intro":                       "The whole process, left to right: a change request is drafted, built and approved, then its revision rolls out through the waves - test waves first, then phased production. Cards link to the change and rollout screens where you act.",
		"pipeline.manage_post":                 "page.",
		"pipeline.manage_pre":                  "Manage on the",
		"pipeline.manual_gate_title":           "manual approval gate",
		"pipeline.no_waves_post":               "page - test waves first, then phases.",
		"pipeline.no_waves_pre":                "No waves configured. Define the wave plan on the",
		"pipeline.nothing_here":                "Nothing here",
		"pipeline.on_target":                   "on target",
		"pipeline.planned_label":               "Planned",
		"pipeline.rolling_out":                 "Rolling out",
		"pipeline.stage_building":              "Building",
		"pipeline.stage_draft":                 "Draft",
		"pipeline.stage_ready":                 "Ready to merge",
		"pipeline.status_word":                 "status",
		"pipeline.title":                       "Deployment pipeline",
		"policies.add_assignment":              "Add assignment",
		"policies.assign_title":                "Assign a policy",
		"policies.col_filter":                  "Filter",
		"policies.col_match":                   "Match",
		"policies.col_rules":                   "Rules",
		"policies.create_filter":               "Create filter",
		"policies.create_filter_title":         "Create a filter",
		"policies.create_policy":               "Create policy",
		"policies.create_policy_title":         "Create a policy",
		"policies.enforced_tooltip":            "enforced",
		"policies.filter_id_label":             "Filter id",
		"policies.filter_prefix":               "filter",
		"policies.filters_help":                "narrow an assignment to matching devices",
		"policies.filters_title":               "Filters",
		"policies.id_placeholder":              "id (lowercase slug)",
		"policies.intro":                       "Reusable setting bundles, bound to scopes by assignments and narrowed by filters. Manage and enforce configuration state across the fleet.",
		"policies.locked_keys_placeholder":     "locked keys, comma-separated",
		"policies.lowercase_slug_placeholder":  "lowercase slug",
		"policies.match_all":                   "all rules",
		"policies.match_any":                   "any rule",
		"policies.no_filter_option":            "no filter (all devices)",
		"policies.no_filters_defined":          "No filters defined.",
		"policies.no_policies":                 "No policies defined.",
		"policies.no_settings":                 "no settings",
		"policies.op_equals":                   "equals",
		"policies.op_in_comma_list":            "in (comma list)",
		"policies.op_not_equals":               "not equals",
		"policies.op_starts_with":              "starts with",
		"policies.payload_config":              "Payload configuration",
		"policies.per_line_post":               "per line; the gate validates.",
		"policies.per_line_pre":                "one",
		"policies.policy_option":               "policy",
		"policies.priority_placeholder":        "priority (tie-break)",
		"policies.settings_placeholder":        "key = value",
		"policies.unassign":                    "unassign",
		"policies.unassigned":                  "unassigned",
		"profile.cli_desc_end":                 " the console uses, authenticated with a personal token above. This build matches the running server, so the CLI and the fleet never drift.",
		"profile.cli_desc_mid":                 " drives the same ",
		"profile.cli_title":                    "Command-line tool",
		"profile.cli_verify_1":                 "Linux x86-64 static binary. Verify with ",
		"profile.cli_verify_2":                 ", then ",
		"profile.create_token":                 "Create a token",
		"profile.effective_roles":              "Effective roles",
		"profile.generate_token":               "Generate token",
		"profile.idp_groups":                   "IdP groups",
		"profile.language":                     "Language",
		"profile.my_tokens":                    "My API tokens",
		"profile.no_ceiling_full":              "no ceiling (full rights)",
		"profile.no_roles":                     "No roles.",
		"profile.no_tokens":                    "No personal tokens.",
		"profile.preferences":                  "Preferences",
		"profile.save_prefs":                   "Save preferences",
		"profile.subject":                      "Subject",
		"profile.timezone":                     "Timezone",
		"profile.title":                        "Profile",
		"profile.token_created":                "Token created",
		"profile.token_name_placeholder":       "what is this token for?",
		"profile.tokens_intro":                 "Personal access tokens for the CLI and API. Each acts as you, snapshotting your groups; a ceiling can only narrow rights. The secret is shown once.",
		"rollout.active_title":                 "Active rollout",
		"rollout.advance_now":                  "Advance now",
		"rollout.all_remaining":                "All remaining",
		"rollout.approve_promote":              "Approve & promote",
		"rollout.at_a_time":                    "at a time",
		"rollout.awaiting_approval":            "Awaiting approval",
		"rollout.complete_label":               "Complete",
		"rollout.configure_rings_first":        "Configure rollout rings first.",
		"rollout.convergence_title":            "Convergence by wave",
		"rollout.deploying_label":              "Deploying",
		"rollout.devices_converged":            "devices converged",
		"rollout.gate_badge":                   "gate",
		"rollout.halt":                         "Halt rollout",
		"rollout.healthy_label":                "healthy",
		"rollout.how_ships_desc":               "The update reaches each wave in order - the next wave only starts once the current one is healthy through its soak window (and you sign off a gated wave). Size a wave by its group (a small canary first, then wider); refine each with soak, health and an approval gate.",
		"rollout.how_ships_title":              "How this rollout ships",
		"rollout.intro":                        "Waves promote in order: each wave must converge healthy through its soak window before the next; a manual-gate wave waits for your sign-off.",
		"rollout.manual_gate":                  "manual gate",
		"rollout.max_at_once_placeholder":      "max at once (0=all)",
		"rollout.max_at_once_title":            "Count-capped canary: release this many devices at a time, widening as each batch converges. 0 releases the whole group.",
		"rollout.min_healthy_placeholder":      "min healthy %",
		"rollout.no_run":                       "No rollout run.",
		"rollout.progression_title":            "Progression",
		"rollout.queued_label":                 "Queued",
		"rollout.require_approval":             "Require manual approval before promoting the next wave",
		"rollout.save_plan":                    "Save plan",
		"rollout.skip_test_wave":               "This plan has no gated test wave - skip (owner override)",
		"rollout.soak_label":                   "soak",
		"rollout.soak_placeholder":             "soak (min)",
		"rollout.soaking_label":                "Soaking",
		"rollout.start":                        "Start rollout",
		"rollout.target_placeholder":           "rev to roll out",
		"rollout.target_revision":              "Target revision",
		"rollout.th_gate":                      "Gate",
		"rollout.th_on_target":                 "On target",
		"rollout.th_wave":                      "Wave",
		"rollout.unused_wave":                  "(unused wave)",
		"rollout.wave_n_label":                 "Wave",
		"rollout.wave_name_placeholder":        "wave name (e.g. Canary, Test, Phase 1)",
		"rollout.wave_plan_desc":               "Ordered waves: test waves first, then rollout phases. Each wave soaks and must be healthy before the next; a manual-gate wave waits for your approval. Saving replaces the whole plan.",
		"rollout.wave_plan_title":              "Wave plan (pipeline)",
		"secret.store_now":                     "Store this secret now; it is not shown again.",
		"secrets.description_placeholder":      "what it is for",
		"secrets.intro_post":                   "of a secret that exists in the secret store (agenix on the device, a Secret in the cluster); secret settings then reference the name, and the build resolves it to a path. No secret ever enters the console or git.",
		"secrets.intro_pre":                    "Sextant never stores a secret value. Register the",
		"secrets.name_field_label":             "Secret name",
		"secrets.name_inline":                  "name",
		"secrets.names_suffix":                 "names",
		"secrets.none_registered":              "No secret references registered yet.",
		"secrets.register":                     "Register",
		"secrets.register_help":                "Enter the name only - the same name the secret has in agenix or the cluster Secret. The value stays in the secret store; Sextant only records the name.",
		"secrets.register_title":               "Register a secret reference",
		"secrets.registered_title":             "Registered secret references",
		"secrets.title":                        "Secrets",
		"service_accounts.account_col":         "Account",
		"service_accounts.active":              "Active service accounts",
		"service_accounts.bindable_hint":       "only groups bound in Access are offered",
		"service_accounts.create_button":       "Create service account",
		"service_accounts.create_title":        "Create a service account",
		"service_accounts.created":             "Service account created",
		"service_accounts.id_hint":             "lowercase slug; becomes svc:<id>",
		"service_accounts.intro":               "Non-human principals for CI, integrations and automation. A service account has its own subject and a snapshot of IdP groups; its rights come from the access bindings for those groups, not from a person. The secret is shown once.",
		"service_accounts.name_placeholder":    "what is this account for?",
		"service_accounts.no_accounts":         "No service accounts yet.",
		"service_accounts.no_ceiling":          "no ceiling (full rights of its groups)",
		"service_accounts.no_groups_1":         "No groups are bound to a role yet. Add a binding on the ",
		"service_accounts.no_groups_2":         " page first; without one this account has no rights.",
		"service_accounts.no_store":            "Service accounts need the database (Postgres is not configured).",
		"service_accounts.org_role":            "Org role",
		"service_accounts.subject_desc_1":      "The subject becomes ",
		"service_accounts.subject_desc_2":      ". Rights follow the groups you bind here.",
		"service_accounts.title":               "Service accounts",
		"settings.accept_risk":                 "Accept risk",
		"settings.apps_help":                   "Additive across the chain: a device gets the union of org, group ancestry and its own lists. Names only (nixpkgs attrs, flathub ids, repo overlays) - never code.",
		"settings.apps_title":                  "Apps at this scope",
		"settings.code_placeholder":            "one item per line (inherit if empty)",
		"settings.col_control":                 "Control",
		"settings.col_effective":               "Effective",
		"settings.col_setting":                 "Setting",
		"settings.col_source":                  "Source",
		"settings.col_value":                   "Value at this scope",
		"settings.control_key_label":           "Control key",
		"settings.default_label":               "default:",
		"settings.editing":                     "You are editing",
		"settings.flow_post":                   "to lock it, so lower scopes cannot change it (the most general locked value wins).",
		"settings.flow_pre":                    "Settings flow down. A value set at the organisation applies to every group and device below it, unless a more specific scope sets its own value. Mark a value",
		"settings.inherits_label":              "inherits",
		"settings.justification":               "Justification",
		"settings.justification_placeholder":   "why this control cannot be met here",
		"settings.keys_suffix":                 "keys",
		"settings.no_acceptances":              "No risk acceptances at this scope.",
		"settings.no_catalog_post":             "and commit it.",
		"settings.no_catalog_pre":              "No catalog published yet. Export one from the overlay repo:",
		"settings.no_secrets_pre":              "no secrets registered -",
		"settings.register_one":                "register one",
		"settings.register_secret_title":       "Register a new secret reference",
		"settings.risk_acceptances_help":       "Accept a control that cannot be met at this scope, with a documented justification. A failing-but-accepted control reads as explained, not open.",
		"settings.risk_acceptances_title":      "Risk acceptances",
		"settings.risk_suffix":                 "risk",
		"settings.scope_help_post":             "locks a value for everything below (most-general wins); a plain value is a default the more specific scope may override. Every change passes the gate and commits to git.",
		"settings.scope_help_pre":              "Values set here apply at the selected scope.",
		"settings.select_device":               "Device...",
		"settings.select_group":                "Group...",
		"settings.admin":                       "Administration",
		"settings.all_groups":                  "All groups",
		"settings.all_devices":                 "All devices",
		"settings.title":                       "Configuration editor",
		"station.bearer_token":                 "Bearer token",
		"station.choose_station":               "Choose a station...",
		"station.credential_created":           "Station credential created",
		"station.credential_instructions":      "Store it on the station now; it is not shown again. Configure the station agent with the endpoint and this bearer token:",
		"station.devices_suffix":               "device(s)",
		"station.go_to_enrollment":             "Go to enrollment",
		"station.image_them_hint":              "Image them from the guided enrollment flow.",
		"station.intro":                        "An imaging station (the \"inspoelstraat\") boots devices over PXE and reports what it sees. This page registers stations and issues their report credential; to image the devices a station has found, go to",
		"station.mint_credential":              "Mint credential",
		"station.no_devices":                   "No devices",
		"station.no_stations":                  "No stations registered yet.",
		"station.open_station":                 "Open station",
		"station.owner_must_register":          "An organisation owner must register one first.",
		"station.pxe_suffix":                   "on this station's PXE network",
		"station.register_button":              "Register station",
		"station.register_desc":                "Give the station a tag; after registering, mint its credential and configure the station agent with the endpoint shown.",
		"station.register_first_below":         "Register your first one below.",
		"station.register_title":               "Register an imaging station",
		"station.report_endpoint":              "Report endpoint",
		"station.site_label":                   "Site",
		"station.station_label":                "Station",
		"station.station_tag_label":            "Station tag",
		"station.title":                        "Imaging stations",
	},
	"nl": {
		"access.active_bindings":               "Actieve rolbindingen",
		"access.approval_desc":                 "Hoe wijzigingen en updates beoordeeld moeten worden voordat ze van kracht worden.",
		"access.approval_flows":                "Goedkeuringsstromen",
		"access.bindings_suffix":               "bindingen",
		"access.dir_not_configured":            "directory-browse niet geconfigureerd; typ de groepsnaam",
		"access.four_eyes_desc":                "een wijziging mag niet worden samengevoegd door de eigen auteur (functiescheiding).",
		"access.four_eyes_label":               "Vier-ogen",
		"access.grant_desc":                    "Koppel een IdP-groep aan een rol binnen een bereik.",
		"access.grant_title":                   "Toegang verlenen",
		"access.intro":                         "Rolbindingen kennen IdP-groepen een rol toe binnen een bereik. Bindingen maken deel uit van de fleet-configuratie: elke wijziging is een beheerste, gecontroleerde git-commit.",
		"access.no_bindings":                   "Geen bindingen; alleen de door de server geconfigureerde basisgroepen zijn van toepassing.",
		"access.require_change_desc":           "configuratiewijzigingen moeten via een beoordeelde change verlopen, nooit via een directe commit.",
		"access.require_change_label":          "Change-request verplicht",
		"access.require_testwave_desc":         "een uitrol moet eerst een gecontroleerde testgolf doorlopen; een owner kan dit per uitrol overslaan.",
		"access.require_testwave_label":        "Testgolf verplicht",
		"access.save_approval_flows":           "Goedkeuringsstromen opslaan",
		"access.select_role":                   "Selecteer een rol...",
		"access.stage_binding":                 "Binding klaarzetten",
		"access.title":                         "Toegangsbeheer",
		"audit.commit":                         "Commit",
		"audit.commit_trail":                   "Configuratie-commitgeschiedenis",
		"audit.download_bundle":                "JSON-bundel downloaden",
		"audit.entries_label":                  "vermeldingen",
		"audit.evidence_desc":                  "Download een ondertekende JSON-bundel voor een periode: elke wijziging, wie deze heeft goedgekeurd en wat is uitgerold. Voor auditors en compliance-reviews.",
		"audit.evidence_export":                "Bewijsexport",
		"audit.from_date":                      "Vanaf datum",
		"audit.intro":                          "Bekijk configuratiewijzigingen en toegangsgeschiedenis. Elke wijziging is een ondertekende git-commit.",
		"audit.no_history":                     "Geen geschiedenis beschikbaar.",
		"audit.title":                          "Audittrail",
		"audit.to_date":                        "Tot datum",
		"audit.what":                           "Wat",
		"audit.when":                           "Wanneer",
		"audit.who":                            "Wie",
		"changes.abandon":                      "Afbreken",
		"changes.build":                        "Bouwen",
		"changes.clear_instead":                "in plaats daarvan wissen",
		"changes.count_suffix":                 "wijzigingen",
		"changes.diff_link":                    "Diff",
		"changes.empty":                        "Nog geen wijzigingen.",
		"changes.id_label":                     "Wijzigings-ID",
		"changes.intro":                        "Een wijziging plaatst bewerkingen op een branch, bouwt tegen de poort en wordt samengevoegd onder het vier-ogenprincipe. Alles is een git-commit.",
		"changes.merge":                        "Samenvoegen",
		"changes.open_button":                  "Wijziging openen",
		"changes.open_title":                   "Wijziging openen",
		"changes.review":                       "Reviewwachtrij",
		"changes.setting_key_placeholder":      "instellingensleutel",
		"changes.slug_placeholder":             "kleine letters, slug",
		"changes.stage_button":                 "Klaarzetten",
		"changes.stage_edit":                   "Bewerking klaarzetten",
		"changes.title_label":                  "Titel",
		"changes.title_placeholder":            "wat doet deze wijziging?",
		"changes.value_placeholder":            "waarde",
		"common.actions":                       "Acties",
		"common.add":                           "+ nieuw",
		"common.apply":                         "Toepassen",
		"common.asset_tag":                     "Assettag",
		"common.cancel":                        "Annuleren",
		"common.ceiling":                       "Plafond",
		"common.class":                         "Klasse",
		"common.clear":                         "Wissen",
		"common.comma_separated":               "kommagescheiden",
		"common.continue":                      "Doorgaan",
		"common.cpu":                           "CPU",
		"common.create":                        "Aanmaken",
		"common.created":                       "Aangemaakt",
		"common.delete":                        "Verwijderen",
		"common.description":                   "Omschrijving",
		"common.device":                        "Apparaat",
		"common.disk":                          "Schijf",
		"common.download":                      "Downloaden",
		"common.edit":                          "bewerken",
		"common.eg":                            "bijv.",
		"common.enforce":                       "Afdwingen",
		"common.expires":                       "Verloopt",
		"common.false":                         "onwaar",
		"common.firmware":                      "Firmware",
		"common.group":                         "Groep",
		"common.groups":                        "Groepen",
		"common.hardware":                      "Hardware",
		"common.hardware_profile":              "Hardwareprofiel",
		"common.id":                            "ID",
		"common.idp_group":                     "IdP-groep",
		"common.inherit":                       "overerven",
		"common.lastused":                      "Laatst gebruikt",
		"common.locked":                        "vergrendeld",
		"common.memory":                        "Geheugen",
		"common.model":                         "Model",
		"common.name":                          "Naam",
		"common.never":                         "nooit",
		"common.never_seen":                    "nooit gezien",
		"common.new_short":                     "+ nieuw",
		"common.no_group":                      "Geen groep",
		"common.none":                          "geen",
		"common.offline":                       "offline",
		"common.online":                        "online",
		"common.optional":                      "optioneel",
		"common.org_default":                   "standaard van organisatie",
		"common.organisation":                  "Organisatie",
		"common.profile":                       "Profiel",
		"common.remove":                        "Verwijderen",
		"common.revoke":                        "Intrekken",
		"common.role":                          "Rol",
		"common.save":                          "Opslaan",
		"common.scope":                         "Bereik",
		"common.select":                        "Selecteer...",
		"common.serial":                        "Serienummer",
		"common.status":                        "Status",
		"common.tag":                           "Tag",
		"common.true":                          "waar",
		"common.ttl_days":                      "TTL (dagen)",
		"common.unknown":                       "onbekend",
		"common.user":                          "Gebruiker",
		"common.value":                         "Waarde",
		"common.vendor":                        "Fabrikant",
		"common.withdraw":                      "Intrekken",
		"device.armed_label":                   "Actief:",
		"device.assign_user":                   "Gebruiker toewijzen",
		"device.assigned_user":                 "Toegewezen gebruiker",
		"device.assigned_user_placeholder":     "toegewezen gebruiker",
		"device.attention":                     "aandacht",
		"device.class_placeholder":             "klasse (laptop, kiosk)",
		"device.col_enforced":                  "Afgedwongen",
		"device.col_provenance":                "Herkomst",
		"device.col_setting":                   "Instelling",
		"device.complete":                      "voltooid",
		"device.confirm_wipe_label":            "Typ de tag om het wissen te bevestigen",
		"device.cores":                         "kernen",
		"device.credential_hint":               "Bewaar dit nu; het wordt niet nog eens getoond. Het apparaat meldt zich hiermee als zichzelf.",
		"device.credential_label":              "Eenmalige referentie",
		"device.effective_config":              "Effectieve configuratie",
		"device.executed":                      "uitgevoerd",
		"device.facts_title":                   "Hardwaregegevens (nixos-facter)",
		"device.hardware_spec_title":           "Hardwarespecificatie",
		"device.identity_title":                "Identiteit",
		"device.last_seen":                     "Laatst gezien",
		"device.lock_device":                   "Apparaat vergrendelen",
		"device.locked_title":                  "vergrendeld",
		"device.lost_stolen_desc":              "Verloren of gestolen apparaat. Vergrendelen is omkeerbaar; wissen vernietigt de schijfversleutelingssleutels en is onomkeerbaar. Elke actie is een geauditeerde commit.",
		"device.manage_desc":                   "Beheeracties voor toewijzing en levenscyclusstatus. Elke wijziging is een gecontroleerde, ondertekende git-commit.",
		"device.manage_title":                  "Apparaat beheren",
		"device.managed_apps":                  "Beheerde applicaties",
		"device.next_label":                    "Volgende:",
		"device.no_apps":                       "Geen applicaties toegewezen.",
		"device.nothing_configured":            "Nog niets geconfigureerd.",
		"device.open_editor":                   "Editor openen",
		"device.overridable_title":             "overschrijfbaar",
		"device.pending_delivery":              "aflevering in behandeling bij volgende check-in",
		"device.posture_waiting":               "Wachten op een statusmelding van de apparaat-agent.",
		"device.raw_document":                  "ruw document",
		"device.reactivate":                    "Heractiveren",
		"device.reactivate_hint":               "komt weer in dienst met een nieuwe referentie",
		"device.reissue_credential":            "Referentie opnieuw uitgeven",
		"device.remote_actions_title":          "Externe acties",
		"device.reported":                      "Gerapporteerd",
		"device.retire":                        "Uitfaseren",
		"device.retired":                       "uitgefaseerd",
		"device.sb_audit_mode":                 "auditmodus",
		"device.sb_enforcing":                  "afdwingend",
		"device.sb_off":                        "uit",
		"device.secure_boot":                   "Secure Boot",
		"device.security_posture":              "Beveiligingsstatus",
		"device.set_class":                     "Klasse instellen",
		"device.set_groups":                    "Groepen instellen",
		"device.tpm2_absent":                   "afwezig",
		"device.tpm2_enrolled":                 "geregistreerd",
		"device.tpm2_present_unbound":          "aanwezig, niet gekoppeld",
		"device.tpm2_unlock":                   "TPM2-ontgrendeling",
		"device.type_overlay":                  "Overlay",
		"device.type_package":                  "Pakket",
		"device.wipe_device":                   "Apparaat wissen",
		"device.wipe_failed":                   "wissen mislukt - niet volledig gewist",
		"device.wipe_refused":                  "geweigerd door apparaat (niet actief / niet vergrendeld)",
		"devices.device_class":                 "Apparaatklasse",
		"devices.enroll_device":                "Apparaat inschrijven",
		"devices.fast_enrollment":              "Snel inschrijven",
		"devices.gitops_managed":               "Beheerd via Git-Ops",
		"devices.no_devices":                   "Nog geen apparaten ingeschreven.",
		"devices.primary_group":                "Primaire groep",
		"devices.subtitle":                     "Nieuwe hardware inrichten en actieve toewijzingen beheren. Elke wijziging aan een apparaat is een gecontroleerde, ondertekende git-commit.",
		"devices.title":                        "Apparatenvloot",
		"devices.validated_hint":               "Gevalideerd door de gate, gecommit naar git.",
		"diff.by":                              "door",
		"diff.no_changes":                      "Nog geen wijzigingen op deze branch.",
		"enroll.batch_desc":                    "Vink de apparaten hieronder aan en schrijf ze allemaal in met één profiel en groep. Elk apparaat krijgt de tag",
		"enroll.batch_title":                   "In één keer meerdere inschrijven",
		"enroll.cancel_job_title":              "Taak annuleren",
		"enroll.device_tag":                    "Apparaattag",
		"enroll.devices_on":                    "Apparaten op",
		"enroll.disk_suffix":                   "schijf",
		"enroll.dispatch_selected":             "Inspoelen starten voor geselecteerde",
		"enroll.dispatch_single":               "Inspoelen starten",
		"enroll.image_device":                  "Dit apparaat inspoelen",
		"enroll.imaging_steps":                 "Inspoelstappen",
		"enroll.jobs_title":                    "Inspoeltaken",
		"enroll.no_stations_post":              ".",
		"enroll.no_stations_pre":               "Nog geen inspoelstations geregistreerd. Registreer er eerst een via de pagina",
		"enroll.on_pxe":                        "op PXE",
		"enroll.profile_name_placeholder":      "profielnaam",
		"enroll.pxe_empty":                     "Nog niets op het PXE-netwerk. Start een apparaat op het inspoelnetwerk van dit station en het verschijnt hier.",
		"enroll.seen_prefix":                   "gezien",
		"enroll.select_station":                "Selecteer een station...",
		"enroll.status_canceled":               "geannuleerd",
		"enroll.status_failed":                 "mislukt",
		"enroll.status_imaging":                "bezig met inspoelen",
		"enroll.status_installed":              "geïnstalleerd",
		"enroll.status_pending":                "in behandeling",
		"enroll.step1_title":                   "Inspoelstation",
		"enroll.subtitle":                      "Apparaten inspoelen vanaf een inspoelstation: kies een station, bekijk wat er op het PXE-netwerk staat en spoel één machine in met merkspecifieke instructies, of een heel rek in één keer.",
		"enroll.suggested":                     "voorgesteld",
		"enroll.tag_prefix":                    "Tagprefix",
		"enroll.title":                         "Inschrijving",
		"error.back":                           "Ga terug",
		"error.title":                          "Dit is niet gelukt",
		"footer.aria_resources":                "Bronnen",
		"footer.audit":                         "Auditlogboek",
		"footer.docs":                          "Documentatie",
		"footer.status":                        "Systeemstatus",
		"footer.support":                       "Ondersteuning",
		"footer.tagline":                       "NixOS-beheerplatform voor het wagenpark",
		"groups.create":                        "Groep aanmaken",
		"groups.create_heading":                "Groep aanmaken",
		"groups.details_title":                 "Groepsdetails",
		"groups.device_count":                  "Aantal apparaten",
		"groups.empty":                         "Nog geen groepen.",
		"groups.follows_head":                  "volgt HEAD",
		"groups.hierarchy_title":               "Organisatiehiërarchie",
		"groups.idp_group_placeholder":         "IdP-groep",
		"groups.idp_mapped":                    "IdP gekoppeld",
		"groups.idp_mapping":                   "IdP-koppeling",
		"groups.intro":                         "Hiërarchische apparaatgroepen, koppelingen met de identiteitsprovider en pin-status. Beleid wordt herleid via organisatie → bovenliggende groepen → groep → apparaat; afgedwongen waarden werken door naar beneden.",
		"groups.legend_devices":                "Apparaten",
		"groups.legend_idp":                    "IdP",
		"groups.legend_pinned":                 "Vastgezet",
		"groups.map_button":                    "Koppelen",
		"groups.map_idp":                       "IdP-groep koppelen",
		"groups.move":                          "Verplaatsen",
		"groups.none_option":                   "- geen -",
		"groups.not_mapped":                    "niet gekoppeld",
		"groups.open_settings":                 "Instellingen openen",
		"groups.owner_actions":                 "Eigenaaracties",
		"groups.parent":                        "Bovenliggende groep",
		"groups.pin_field":                     "Pin",
		"groups.pinned_badge":                  "vastgezet",
		"groups.pinned_to":                     "Vastgezet op",
		"groups.remove_group":                  "Groep verwijderen",
		"groups.reparent":                      "Verplaatsen",
		"groups.root":                          "(root)",
		"groups.select_hint":                   "Selecteer een groep in de hiërarchie om de details en eigenaaracties te bekijken.",
		"groups.slug_placeholder":              "kleine letters, slug",
		"groups.title":                         "Apparaatgroepen",
		"groups.unmapped":                      "Niet gekoppeld",
		"groups.unmapped_option":               "- niet gekoppeld -",
		"layout.breadcrumb_aria":               "Kruimelpad",
		"layout.enroll_device":                 "Apparaat inschrijven",
		"layout.enroll_title":                  "Apparaat inschrijven",
		"layout.review_changes_title":          "Openstaande wijzigingen beoordelen",
		"layout.section_configuration":         "Configuratie",
		"layout.section_fleet":                 "Wagenpark",
		"layout.section_governance":            "Governance",
		"layout.section_shipping":              "Uitlevering",
		"layout.staged_rollout_title":          "Gefaseerde uitrol",
		"layout.tagline":                       "Beheerplatform voor het wagenpark",
		"layout.unread_suffix":                 "ongelezen",
		"nav.access":                           "Toegang",
		"nav.audit":                            "Audit",
		"nav.changes":                          "Wijzigingen",
		"nav.delivery":                         "Uitlevering",
		"nav.devices":                          "Apparaten",
		"nav.enroll":                           "Inschrijving",
		"nav.groups":                           "Groepen",
		"nav.integrations":                     "Integraties",
		"nav.mail":                             "E-mail (SMTP)",
		"nav.org":                              "Organisatie",
		"nav.profile":                          "Profiel",
		"org.title":                            "Organisatie-instellingen",
		"org.subtitle":                         "Globale instellingen voor deze organisatie. Sextant draait één deployment per organisatie, dus deze gelden voor de hele vloot.",
		"org.mail_desc":                        "Stel in hoe deze organisatie notificatie-e-mail verstuurt (SMTP).",
		"org.sa_desc":                          "Machine-credentials voor CI en automatisering.",
		"org.audit_desc":                       "Wie wijzigde wat, en wanneer.",
		"org.overlays_desc":                    "Herbruikbare Nix-overlay-modules gepubliceerd naar de vloot.",
		"org.secrets_desc":                     "Verwijzingen naar secrets die in de secret-store leven.",
		"org.stations_desc":                    "Stel inspoelstations in die nieuwe apparaten inschrijven.",
		"org.defaults":                         "Presentatie-standaarden",
		"org.default_locale":                   "Taal",
		"org.default_timezone":                 "Tijdzone",
		"org.defaults_help":                    "Organisatie-standaarden ingesteld bij deployment; de eigen voorkeuren van een gebruiker gaan voor.",
		"nav.overlays":                         "Overlays",
		"nav.overview":                         "Overzicht",
		"nav.pipeline":                         "Pijplijn",
		"nav.policies":                         "Beleid",
		"nav.rollout":                          "Uitrol",
		"nav.secrets":                          "Geheimen",
		"nav.serviceaccounts":                  "Service-accounts",
		"nav.settings":                         "Instellingen",
		"nav.signout":                          "Uitloggen",
		"nav.stations":                         "Imaging-stations",
		"overlays.help_text":                   "Wordt geïmporteerd door elk apparaat waarvan het bereik deze overlay selecteert. Moet evalueren en bouwen, anders wordt de opslag geweigerd.",
		"overlays.intro_post":                  "opties declareert, verschijnen deze in Instellingen en Integraties om per bereik af te stellen. Overlays tellen op door de bereikketen heen.",
		"overlays.intro_pre":                   "Eenmalig coderen, daarna beheren via de interface. Schrijf hier een aangepaste Nix-module voor een apparaatklasse (IoT, k8s-node, kassaterminal) - elke opslag moet de Nix-evaluatie-gate doorstaan voordat deze wordt gecommit. Beheer de module daarna zonder code aan te raken: wijs deze toe aan een bereik (organisatie, groep of apparaat) vanuit Instellingen, en als de module",
		"overlays.module_label":                "Module (Nix)",
		"overlays.modules_title":               "Modules",
		"overlays.name_label":                  "Overlaynaam",
		"overlays.new_overlay_label":           "nieuwe overlay",
		"overlays.none_yet":                    "Nog geen overlays. Schrijf uw eerste rechts.",
		"overlays.save_validate":               "Opslaan & valideren",
		"overlays.start_template":              "Begin met een klassjabloon",
		"overlays.title":                       "Overlays",
		"page.integrations.available":          "beschikbaar",
		"page.integrations.clear":              "Wissen",
		"page.integrations.inherit":            "overerven",
		"page.integrations.no_secrets":         "geen geheimen geregistreerd -",
		"page.integrations.none":               "geen",
		"page.integrations.not_published":      "niet gepubliceerd",
		"page.integrations.not_published_post": "opties gepubliceerd. Voeg de module toe aan de overlay en exporteer de catalogus om dit hier te configureren.",
		"page.integrations.not_published_pre":  "Deze overlay heeft nog geen",
		"page.integrations.not_set":            "niet ingesteld",
		"page.integrations.open_editor":        "Openen in de configuratie-editor",
		"page.integrations.register_one":       "registreer er een",
		"page.integrations.register_title":     "Registreer een nieuwe geheimreferentie",
		"page.integrations.risk_suffix":        "risico",
		"page.integrations.secret_tag":         "geheim",
		"page.integrations.subtitle":           "Verbind het wagenpark met NetBird, uw directory en Wazuh. Dit zijn device-side opties die de overlay publiceert in de catalogus; stel ze eenmalig in op organisatieniveau en ze werken door naar elk apparaat. Geheime waarden worden opgeslagen als referenties (nooit het geheim zelf).",
		"page.mail.from":                       "Afzenderadres",
		"page.mail.host":                       "SMTP-host",
		"page.mail.opt_none":                   "Geen (alleen lokale relay)",
		"page.mail.opt_starttls":               "STARTTLS (587)",
		"page.mail.opt_tls":                    "TLS (465)",
		"page.mail.password":                   "Wachtwoord",
		"page.mail.port":                       "Poort",
		"page.mail.pw_disabled":                "Rechtstreeks een wachtwoord invoeren is uitgeschakeld: er is geen versleutelingssleutel geconfigureerd op deze instantie. Gebruik hierboven een geheimreferentie.",
		"page.mail.pw_placeholder_keep":        "leeg laten om het huidige wachtwoord te behouden",
		"page.mail.pw_placeholder_new":         "invoeren om versleuteld op te slaan",
		"page.mail.recommended":                "(aanbevolen)",
		"page.mail.secretref_hint":             "Het wachtwoord staat in agenix of een cluster-Secret; Sextant leest alleen de naam. Er komt niets geheims in git of de console terecht.",
		"page.mail.secretref_label":            "Naam geheimreferentie",
		"page.mail.security":                   "Beveiliging",
		"page.mail.send_test":                  "Test verzenden",
		"page.mail.send_test_btn":              "Test verzenden",
		"page.mail.send_test_hint":             "Bewijs de instellingen door een bericht te verzenden. Gebruikt de opgeslagen configuratie exact zoals meldingen dat zullen doen.",
		"page.mail.send_to":                    "Verzenden naar",
		"page.mail.sent":                       "Testbericht verzonden. Controleer de inbox.",
		"page.mail.stored_encrypted":           "(versleuteld opgeslagen)",
		"page.mail.subtitle":                   "Hoe deze organisatie meldings-e-mail verzendt, op haar eigen domein. Meldingen in de applicatie werken altijd; configureer hier SMTP om ze ook per e-mail te bezorgen.",
		"page.mail.typepw_hint":                "Hier ingevoerd wordt het wachtwoord verzegeld met de instantiesleutel en opgeslagen in Postgres. Laat leeg om een referentie of de bestaande waarde te behouden.",
		"page.mail.typepw_label":               "...of typ een wachtwoord",
		"page.mail.unavailable":                "E-mail vereist de Postgres-opslag, die niet is geconfigureerd op deze instantie.",
		"page.mail.username":                   "Gebruikersnaam",
		"page.mail.username_hint":              "(leeg = anonieme relay)",
		"page.notifications.empty":             "U bent helemaal bij. Niets te lezen.",
		"page.notifications.mark_all_read":     "Alles als gelezen markeren",
		"page.notifications.subtitle":          "Goedkeuringen die op u wachten, wijzigingen die u heeft aangemaakt, en gebeurtenissen in het wagenpark. Openen markeert een melding als gelezen.",
		"page.notifications.title":             "Meldingen",
		"page.notifications.unavailable":       "Meldingen vereisen de Postgres-opslag, die niet is geconfigureerd op deze instantie.",
		"page.notifications.unread":            "Ongelezen",
		"page.overview.all_changes":            "Alle wijzigingen ->",
		"page.overview.all_devices":            "Alle apparaten ->",
		"page.overview.approval_by":            "door",
		"page.overview.approval_ready":         "- succesvol gebouwd, gereed om samen te voegen",
		"page.overview.awaiting_approval":      "Wacht op uw goedkeuring",
		"page.overview.cli_desc_mid":           "en",
		"page.overview.cli_desc_post":          "in.",
		"page.overview.cli_desc_pre":           "Dezelfde acties, scriptbaar. Stel eerst",
		"page.overview.cli_toolbelt":           "CLI-gereedschap",
		"page.overview.col_device":             "Apparaat",
		"page.overview.col_phase":              "Fase",
		"page.overview.col_revision":           "Revisie",
		"page.overview.col_state":              "Status",
		"page.overview.fleet_status":           "Status wagenpark",
		"page.overview.legend_error":           "storing",
		"page.overview.legend_prefix":          "Een cel per apparaat",
		"page.overview.needs_attention":        "Vereist aandacht",
		"page.overview.no_checkins":            "Nog geen meldingen.",
		"page.overview.no_devices":             "Nog geen apparaten die zich melden.",
		"page.overview.recent_activity":        "Recente apparaatactiviteit",
		"page.overview.start_enrollment":       "Inschrijving starten",
		"page.overview.stat_devices":           "Apparaten",
		"page.overview.stat_groups":            "Groepen",
		"page.overview.stat_online":            "Online",
		"page.overview.stat_open_changes":      "Openstaande wijzigingen",
		"page.overview.stat_policies":          "Beleid",
		"page.overview.subtitle":               "Actuele status van het wagenpark - elk cijfer is echt, afkomstig uit het configuratieplatform en apparaatmeldingen.",
		"page.overview.title":                  "Overzicht wagenpark",
		"pipeline.group_label":                 "groep",
		"pipeline.intro":                       "Het volledige proces, van links naar rechts: een wijzigingsverzoek wordt opgesteld, gebouwd en goedgekeurd, waarna de revisie via de golven wordt uitgerold - eerst testgolven, dan gefaseerde productie. Kaarten verwijzen naar de wijzigings- en uitrolschermen waar u actie onderneemt.",
		"pipeline.manage_post":                 "pagina.",
		"pipeline.manage_pre":                  "Beheer dit op de",
		"pipeline.manual_gate_title":           "handmatige goedkeuringspoort",
		"pipeline.no_waves_post":               "pagina - eerst testgolven, dan fasen.",
		"pipeline.no_waves_pre":                "Geen golven geconfigureerd. Definieer het golfplan op de",
		"pipeline.nothing_here":                "Niets hier",
		"pipeline.on_target":                   "op doel",
		"pipeline.planned_label":               "Gepland",
		"pipeline.rolling_out":                 "Bezig met uitrollen van",
		"pipeline.stage_building":              "Wordt gebouwd",
		"pipeline.stage_draft":                 "Concept",
		"pipeline.stage_ready":                 "Klaar om samen te voegen",
		"pipeline.status_word":                 "status",
		"pipeline.title":                       "Implementatiepijplijn",
		"policies.add_assignment":              "Toewijzing toevoegen",
		"policies.assign_title":                "Beleid toewijzen",
		"policies.col_filter":                  "Filter",
		"policies.col_match":                   "Overeenkomst",
		"policies.col_rules":                   "Regels",
		"policies.create_filter":               "Filter aanmaken",
		"policies.create_filter_title":         "Een filter aanmaken",
		"policies.create_policy":               "Beleid aanmaken",
		"policies.create_policy_title":         "Een beleid aanmaken",
		"policies.enforced_tooltip":            "afgedwongen",
		"policies.filter_id_label":             "Filter-id",
		"policies.filter_prefix":               "filter",
		"policies.filters_help":                "beperk een toewijzing tot overeenkomende apparaten",
		"policies.filters_title":               "Filters",
		"policies.id_placeholder":              "id (kleine letters, slug)",
		"policies.intro":                       "Herbruikbare bundels van instellingen, gekoppeld aan bereiken via toewijzingen en verfijnd met filters. Beheer en handhaaf de configuratiestatus over het gehele wagenpark.",
		"policies.locked_keys_placeholder":     "vergrendelde sleutels, kommagescheiden",
		"policies.lowercase_slug_placeholder":  "kleine letters, slug",
		"policies.match_all":                   "alle regels",
		"policies.match_any":                   "een van de regels",
		"policies.no_filter_option":            "geen filter (alle apparaten)",
		"policies.no_filters_defined":          "Geen filters gedefinieerd.",
		"policies.no_policies":                 "Geen beleid gedefinieerd.",
		"policies.no_settings":                 "geen instellingen",
		"policies.op_equals":                   "is gelijk aan",
		"policies.op_in_comma_list":            "in (kommalijst)",
		"policies.op_not_equals":               "is niet gelijk aan",
		"policies.op_starts_with":              "begint met",
		"policies.payload_config":              "Payload-configuratie",
		"policies.per_line_post":               "per regel; de gate valideert.",
		"policies.per_line_pre":                "een",
		"policies.policy_option":               "beleid",
		"policies.priority_placeholder":        "prioriteit (bij gelijke stand)",
		"policies.settings_placeholder":        "sleutel = waarde",
		"policies.unassign":                    "toewijzing opheffen",
		"policies.unassigned":                  "niet toegewezen",
		"profile.cli_desc_end":                 " aan als de console, geauthenticeerd met een persoonlijk token hierboven. Deze build komt overeen met de draaiende server, zodat de CLI en het machinepark nooit uit de pas lopen.",
		"profile.cli_desc_mid":                 " stuurt dezelfde ",
		"profile.cli_title":                    "Opdrachtregeltool",
		"profile.cli_verify_1":                 "Linux x86-64 statische binary. Verifieer met ",
		"profile.cli_verify_2":                 ", en vervolgens ",
		"profile.create_token":                 "Token aanmaken",
		"profile.effective_roles":              "Effectieve rollen",
		"profile.generate_token":               "Token genereren",
		"profile.idp_groups":                   "IdP-groepen",
		"profile.language":                     "Taal",
		"profile.my_tokens":                    "Mijn API-tokens",
		"profile.no_ceiling_full":              "geen plafond (volledige rechten)",
		"profile.no_roles":                     "Geen rollen.",
		"profile.no_tokens":                    "Geen persoonlijke tokens.",
		"profile.preferences":                  "Voorkeuren",
		"profile.save_prefs":                   "Voorkeuren opslaan",
		"profile.subject":                      "Subject",
		"profile.timezone":                     "Tijdzone",
		"profile.title":                        "Profiel",
		"profile.token_created":                "Token aangemaakt",
		"profile.token_name_placeholder":       "waarvoor dient dit token?",
		"profile.tokens_intro":                 "Persoonlijke toegangstokens voor de CLI en API. Elk token handelt namens u met een momentopname van uw groepen; een plafond kan rechten alleen beperken. Het geheim wordt eenmalig getoond.",
		"rollout.active_title":                 "Actieve uitrol",
		"rollout.advance_now":                  "Nu doorzetten",
		"rollout.all_remaining":                "Alle overige",
		"rollout.approve_promote":              "Goedkeuren en promoveren",
		"rollout.at_a_time":                    "tegelijk",
		"rollout.awaiting_approval":            "Wacht op goedkeuring",
		"rollout.complete_label":               "Voltooid",
		"rollout.configure_rings_first":        "Configureer eerst de uitrolringen.",
		"rollout.convergence_title":            "Convergentie per golf",
		"rollout.deploying_label":              "Wordt uitgerold",
		"rollout.devices_converged":            "apparaten geconvergeerd",
		"rollout.gate_badge":                   "poort",
		"rollout.halt":                         "Uitrol stoppen",
		"rollout.healthy_label":                "gezond",
		"rollout.how_ships_desc":               "De update bereikt elke golf in volgorde - de volgende golf start pas zodra de huidige gezond is doorheen de rijpingsperiode (en u een golf met goedkeuringsvereiste heeft geaccordeerd). Bepaal de omvang van een golf via de groep (eerst een kleine canary, daarna breder); verfijn elke golf met rijping, gezondheid en een goedkeuringspoort.",
		"rollout.how_ships_title":              "Hoe deze uitrol verloopt",
		"rollout.intro":                        "Golven worden in volgorde gepromoveerd: elke golf moet gezond convergeren binnen de rijpingsperiode voordat de volgende start; een golf met handmatige goedkeuring wacht op uw akkoord.",
		"rollout.manual_gate":                  "handmatige poort",
		"rollout.max_at_once_placeholder":      "max. tegelijk (0=alle)",
		"rollout.max_at_once_title":            "Canary met aantalslimiet: maak dit aantal apparaten tegelijk vrij, steeds breder naarmate elke batch convergeert. 0 geeft de hele groep in één keer vrij.",
		"rollout.min_healthy_placeholder":      "min. gezond %",
		"rollout.no_run":                       "Geen actieve uitrol.",
		"rollout.progression_title":            "Voortgang",
		"rollout.queued_label":                 "In wachtrij",
		"rollout.require_approval":             "Handmatige goedkeuring vereisen voordat de volgende golf wordt gepromoveerd",
		"rollout.save_plan":                    "Plan opslaan",
		"rollout.skip_test_wave":               "Dit plan heeft geen afgeschermde testgolf - overslaan (overschrijving door eigenaar)",
		"rollout.soak_label":                   "rijping",
		"rollout.soak_placeholder":             "rijping (min)",
		"rollout.soaking_label":                "Rijpt",
		"rollout.start":                        "Uitrol starten",
		"rollout.target_placeholder":           "revisie om uit te rollen",
		"rollout.target_revision":              "Doelrevisie",
		"rollout.th_gate":                      "Poort",
		"rollout.th_on_target":                 "Op doel",
		"rollout.th_wave":                      "Golf",
		"rollout.unused_wave":                  "(ongebruikte golf)",
		"rollout.wave_n_label":                 "Golf",
		"rollout.wave_name_placeholder":        "naam van de golf (bijv. Canary, Test, Fase 1)",
		"rollout.wave_plan_desc":               "Golven in volgorde: eerst testgolven, dan uitrolfasen. Elke golf rijpt en moet gezond zijn voordat de volgende start; een golf met handmatige poort wacht op uw goedkeuring. Opslaan vervangt het volledige plan.",
		"rollout.wave_plan_title":              "Golfplan (pipeline)",
		"secret.store_now":                     "Bewaar dit geheim nu; het wordt niet nog eens getoond.",
		"secrets.description_placeholder":      "waarvoor het dient",
		"secrets.intro_post":                   "van een geheim dat bestaat in de geheimenopslag (agenix op het apparaat, een Secret in het cluster); geheime instellingen verwijzen daarna naar de naam, en de build lost deze op naar een pad. Er komt nooit een geheim in de console of in git terecht.",
		"secrets.intro_pre":                    "Sextant slaat nooit een geheime waarde op. Registreer de",
		"secrets.name_field_label":             "Naam geheim",
		"secrets.name_inline":                  "naam",
		"secrets.names_suffix":                 "namen",
		"secrets.none_registered":              "Nog geen verwijzingen naar geheimen geregistreerd.",
		"secrets.register":                     "Registreren",
		"secrets.register_help":                "Voer alleen de naam in - dezelfde naam die het geheim heeft in agenix of de cluster-Secret. De waarde blijft in de geheimenopslag; Sextant registreert alleen de naam.",
		"secrets.register_title":               "Registreer een verwijzing naar een geheim",
		"secrets.registered_title":             "Geregistreerde verwijzingen naar geheimen",
		"secrets.title":                        "Geheimen",
		"service_accounts.account_col":         "Account",
		"service_accounts.active":              "Actieve service-accounts",
		"service_accounts.bindable_hint":       "alleen groepen gebonden in Toegang worden aangeboden",
		"service_accounts.create_button":       "Service-account aanmaken",
		"service_accounts.create_title":        "Service-account aanmaken",
		"service_accounts.created":             "Service-account aangemaakt",
		"service_accounts.id_hint":             "kleine letters, slug; wordt svc:<id>",
		"service_accounts.intro":               "Niet-menselijke principals voor CI, integraties en automatisering. Een service-account heeft een eigen subject en een momentopname van IdP-groepen; de rechten komen uit de toegangsbindingen voor die groepen, niet van een persoon. Het geheim wordt eenmalig getoond.",
		"service_accounts.name_placeholder":    "waarvoor dient dit account?",
		"service_accounts.no_accounts":         "Nog geen service-accounts.",
		"service_accounts.no_ceiling":          "geen plafond (volledige rechten van de groepen)",
		"service_accounts.no_groups_1":         "Er zijn nog geen groepen aan een rol gebonden. Voeg eerst een binding toe op de ",
		"service_accounts.no_groups_2":         "-pagina; zonder binding heeft dit account geen rechten.",
		"service_accounts.no_store":            "Service-accounts hebben de database nodig (Postgres is niet geconfigureerd).",
		"service_accounts.org_role":            "Organisatierol",
		"service_accounts.subject_desc_1":      "Het subject wordt ",
		"service_accounts.subject_desc_2":      ". Rechten volgen de groepen die u hier koppelt.",
		"service_accounts.title":               "Service-accounts",
		"settings.accept_risk":                 "Risico accepteren",
		"settings.apps_help":                   "Optellend over de keten: een apparaat krijgt de unie van organisatie, groep-afstamming en zijn eigen lijsten. Alleen namen (nixpkgs-attributen, flathub-id's, repo-overlays) - nooit code.",
		"settings.apps_title":                  "Apps op dit bereik",
		"settings.code_placeholder":            "een item per regel (erft over indien leeg)",
		"settings.col_control":                 "Beheersmaatregel",
		"settings.col_effective":               "Effectief",
		"settings.col_setting":                 "Instelling",
		"settings.col_source":                  "Bron",
		"settings.col_value":                   "Waarde op dit bereik",
		"settings.control_key_label":           "Sleutel beheersmaatregel",
		"settings.default_label":               "standaard:",
		"settings.editing":                     "U bewerkt",
		"settings.flow_post":                   "om deze te vergrendelen, zodat onderliggende bereiken deze niet kunnen wijzigen (de meest algemene vergrendelde waarde wint).",
		"settings.flow_pre":                    "Instellingen stromen naar beneden. Een waarde die op organisatieniveau is ingesteld geldt voor elke groep en elk apparaat daaronder, tenzij een specifieker bereik een eigen waarde instelt. Markeer een waarde als",
		"settings.inherits_label":              "erft over",
		"settings.justification":               "Motivering",
		"settings.justification_placeholder":   "waarom deze maatregel hier niet gehaald kan worden",
		"settings.keys_suffix":                 "sleutels",
		"settings.no_acceptances":              "Geen risicoacceptaties op dit bereik.",
		"settings.no_catalog_post":             "en commit deze.",
		"settings.no_catalog_pre":              "Nog geen catalogus gepubliceerd. Exporteer er een uit de overlay-repository:",
		"settings.no_secrets_pre":              "geen geheimen geregistreerd -",
		"settings.register_one":                "registreer er een",
		"settings.register_secret_title":       "Registreer een nieuwe verwijzing naar een geheim",
		"settings.risk_acceptances_help":       "Accepteer een beheersmaatregel die op dit bereik niet gehaald kan worden, met een gedocumenteerde motivering. Een falende maar geaccepteerde maatregel wordt getoond als verklaard, niet als open.",
		"settings.risk_acceptances_title":      "Risicoacceptaties",
		"settings.risk_suffix":                 "risico",
		"settings.scope_help_post":             "vergrendelt een waarde voor alles daaronder (het meest algemene niveau wint); een gewone waarde is een standaardwaarde die een specifieker bereik mag overschrijven. Elke wijziging doorloopt de gate en wordt vastgelegd in git.",
		"settings.scope_help_pre":              "Waarden die u hier instelt gelden voor het geselecteerde bereik.",
		"settings.select_device":               "Apparaat...",
		"settings.select_group":                "Groep...",
		"settings.admin":                       "Beheer",
		"settings.all_groups":                  "Alle groepen",
		"settings.all_devices":                 "Alle apparaten",
		"settings.title":                       "Configuratie-editor",
		"station.bearer_token":                 "Bearer-token",
		"station.choose_station":               "Kies een station...",
		"station.credential_created":           "Stationreferentie aangemaakt",
		"station.credential_instructions":      "Bewaar het nu op het station; het wordt niet nog eens getoond. Configureer de stationagent met het endpoint en dit bearer-token:",
		"station.devices_suffix":               "apparaat/apparaten",
		"station.go_to_enrollment":             "Naar inschrijving",
		"station.image_them_hint":              "Spoel ze in via de begeleide inschrijfstroom.",
		"station.intro":                        "Een inspoelstation (de \"inspoelstraat\") start apparaten op via PXE en meldt wat het aantreft. Deze pagina registreert stations en geeft hun rapportagetoken uit; ga voor het inspoelen van gevonden apparaten naar",
		"station.mint_credential":              "Referentie aanmaken",
		"station.no_devices":                   "Geen apparaten",
		"station.no_stations":                  "Nog geen stations geregistreerd.",
		"station.open_station":                 "Station openen",
		"station.owner_must_register":          "Een organisatie-eigenaar moet er eerst een registreren.",
		"station.pxe_suffix":                   "op het PXE-netwerk van dit station",
		"station.register_button":              "Station registreren",
		"station.register_desc":                "Geef het station een tag; maak na registratie de referentie aan en configureer de stationagent met het getoonde endpoint.",
		"station.register_first_below":         "Registreer hieronder je eerste station.",
		"station.register_title":               "Inspoelstation registreren",
		"station.report_endpoint":              "Rapportage-endpoint",
		"station.site_label":                   "Locatie",
		"station.station_label":                "Station",
		"station.station_tag_label":            "Stationtag",
		"station.title":                        "Inspoelstations",
	},
}
